### PR TITLE
MacOS support added

### PR DESCRIPTION
**Pull request by dizda**

### CODE REVIEW

**Review by jacobsacco — APPROVED** [review]

**Comment by dizda** [comment]
Is there any chance to make a release out of it? 🙏

**Comment by jacobsacco** [comment]
I'm working on some bug fixes and refinements that I'd been putting off right now. as soon as I finish these, I'll put out a release! Sorry about the delay in the first place

**Comment by dizda** [comment]
Super, looking forward to it!

**Comment by jacobsacco** [comment]
Version 8.1 was just published with the contents of this pull! (and other things as well)

**Comment by dizda** [comment]
Thank you my friend! <3

**Pull request merged**
